# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ship < Formula
  desc "Launch your code with one click"
  homepage "https://spaceship.run"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onspaceship/ship/releases/download/v0.0.2/ship_0.0.2_darwin_amd64.tar.gz"
      sha256 "e112a9e06b2f26279709a2be559f13278a7f3f2023d3acca8ce07130924b3545"

      def install
        bin.install "ship"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onspaceship/ship/releases/download/v0.0.2/ship_0.0.2_darwin_arm64.tar.gz"
      sha256 "f8a42482bbb6f86c5e9b4e452954ed3807a0fe0451dba96163860b84e92dc5b0"

      def install
        bin.install "ship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onspaceship/ship/releases/download/v0.0.2/ship_0.0.2_linux_arm64.tar.gz"
      sha256 "be7016d16c1682519239701b781f1bc3f775f43e0295eecdda03260c0f2533cf"

      def install
        bin.install "ship"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/onspaceship/ship/releases/download/v0.0.2/ship_0.0.2_linux_amd64.tar.gz"
      sha256 "80bb9b5eb070a3294b4b75d376999437f67cdbd6c533ace16c13510637cb16e9"

      def install
        bin.install "ship"
      end
    end
  end
end
