# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ship < Formula
  desc "Launch your code with one click"
  homepage "https://spaceship.run"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/onspaceship/ship/releases/download/v0.0.1/ship_0.0.1_darwin_arm64.tar.gz"
      sha256 "0c97d9aced0cb7598d78a1f59eca0d6027acc9976c211e57973684bda92b4364"

      def install
        bin.install "ship"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/onspaceship/ship/releases/download/v0.0.1/ship_0.0.1_darwin_amd64.tar.gz"
      sha256 "42507e2ef0a6ce9c516f01fd055fb733a39feca6ec74196c87bc63e4dd44d15b"

      def install
        bin.install "ship"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onspaceship/ship/releases/download/v0.0.1/ship_0.0.1_linux_arm64.tar.gz"
      sha256 "0dbff1d9b8367e13b2e4b99993475b3c580b4b6c9a49ef5e1063730543f615fb"

      def install
        bin.install "ship"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/onspaceship/ship/releases/download/v0.0.1/ship_0.0.1_linux_amd64.tar.gz"
      sha256 "863073d8b2b43b4ef9f29c26c11fc68ebe20b410464a920b71b5e87f697fe875"

      def install
        bin.install "ship"
      end
    end
  end
end
